apiVersion: apps/v1
kind: Deployment
metadata:
  name: mszlibd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mszlibd
  template:
    metadata:
      labels:
        app: mszlibd
    spec:
      containers:
      - image: okteto/mszlibd:node
        name: mszlibd

---

apiVersion: v1
kind: Service
metadata:
  name: mszlibd
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "mszlibd"
    port: 3000
  selector:
    app: mszlibd
